# Generated by Django 4.1.5 on 2023-02-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='author',
        ),
    ]
